spring:
#  jpa:
#    generate-ddl: true
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

moviefun:
  datasources:
    movies:
      url: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: moviefun
      password: moviefun
    albums:
      url: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: moviefun
      password: moviefun