server.port: 8082

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: moviefun
    password: moviefun

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG
